name: Publish to Maven Central

on:
  push:
    branches:
      - release  # Update this to your main branch if needed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Generate a new GPG key pair
      - name: Generate GPG key
        run: |
          echo -e "Key-Type: default\nKey-Length: 2048\nSubkey-Type: default\nName-Real: GitHub Actions\nName-Email: actions@github.com\nExpire-Date: 0\nPassphrase: ${{ secrets.GPG_PASSPHRASE }}\n%commit\n%echo done" > gen-key-script
          gpg --batch --generate-key gen-key-script
          rm gen-key-script
          gpg --list-secret-keys --keyid-format LONG
        shell: bash

      # Export the GPG key ID
      - name: Extract GPG key ID
        id: gpg
        run: |
          KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep 'sec' | awk '{print $2}' | cut -d'/' -f2)
          echo "KEY_ID=$KEY_ID" >> $GITHUB_ENV
        shell: bash

      # Export GPG private key
      - name: Export GPG private key
        run: |
          gpg --export-secret-keys --armor $KEY_ID > private.key
        shell: bash

      # Set up Gradle properties
      - name: Set up gradle.properties
        run: |
          echo "signing.gnupg.executable=gpg" >> ~/.gradle/gradle.properties
          echo "signing.gnupg.keyName=$KEY_ID" >> ~/.gradle/gradle.properties
          echo "signing.gnupg.passphrase=${{ secrets.GPG_PASSPHRASE }}" >> ~/.gradle/gradle.properties
          echo "ossrhUsername=${{ secrets.OSSRH_USERNAME }}" >> ~/.gradle/gradle.properties
          echo "ossrhPassword=${{ secrets.OSSRH_PASSWORD }}" >> ~/.gradle/gradle.properties
        shell: bash

      # Grant execute permission for Gradle wrapper
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Build and publish to Maven Central
      - name: Build and publish
        run: ./gradlew clean build publish --no-daemon

      # Clean up GPG keys
      - name: Clean up GPG keys
        run: |
          rm private.key
          gpg --batch --yes --delete-secret-keys $KEY_ID
          gpg --batch --yes --delete-keys $KEY_ID
        shell: bash
